---
title: "GSA ChIP Seq Data Analysis Script"
author: "Shaurya Jauhari"
date: "3/1/2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Installing packages of GSA tools

```{r GSA tools}
source('http://www.bioconductor.org/biocLite.R')
BiocManager::install('seq2pathway')
BiocManager::install('enrichR')
BiocManager::install('broadenrich')
BiocManager::install('chipenrich')
```
## Loading Benchmark dataset


```{r sourcing the compiled gold standard benchmark dataset }

install.packages("GSAChIPSeqGold_0.1.1.tar.gz", repos = NULL, type = "source")

```

## Testing individual data in benchmark dataset with 
## each GSA tool package
## Seq2Pathway

```{r}
library(GSAChIPSeqGold)
library(seq2pathway)
library(rtracklayer)
library(chipenrich)

## For making maximum memory available to R session. 
memory.size(max = TRUE)

## Also, since several of the tools don't acknowledge the mitochondrial DNA ("chrMT") entries have to be removed from the BED files.

regenerated_samples <- list()
seq2pathway_results <- list()
for (i in 31:length(ChIPSeqSamples))
{
#  export.bed(Samples_in_BED[[i]],format="bed",con = paste("./regenerated_samples/",paste(eval(parse(text="ChIPSeqSamples[i]")),".bed", sep = "")))
  regenerated_samples[[i]] <- read_bed(paste("./regen/",paste(eval(parse(text="ChIPSeqSamples[i]")),".bed", sep = ""), sep = ""))
  seq2pathway_results[[i]] <- runseq2pathway(regenerated_samples[[i]], genome = "hg19")
}
 saveRDS(seq2pathway_results, file = "./Results/seq2pathway/seq2pathway_results_31_106")
 rm(seq2pathway_results)

chipenrich_results <- list()
for (i in 1:length(ChIPSeqSamples))
{
  chipenrich_results[[i]] <- chipenrich(peaks = paste("./regen/",paste(eval(parse(text="ChIPSeqSamples[i]")),".bed", sep = ""), sep = ""), out_name = NULL, genesets = c("GOBP", "GOCC", "GOMF", "kegg_pathway"), genome = "hg19", qc_plots = FALSE, n_cores = 1)
}
 saveRDS(chipenrich_results, file = "./Results/chipenrich/chipenrich_results")
 rm(chipenrich_results)

 
broadenrich_results <- list()
for (i in 1:length(ChIPSeqSamples))
{
  broadenrich_results[[i]] <- broadenrich(peaks = paste("./regen/",paste(eval(parse(text="ChIPSeqSamples[i]")),".bed", sep = ""), sep = ""), out_name = NULL, genesets = c("GOBP", "GOCC", "GOMF", "kegg_pathway"), genome = "hg19", qc_plots = FALSE, n_cores = 1)
}
 saveRDS(broadenrich_results, file = "./Results/broadenrich/broadenrich_results")
 rm(broadenrich_results)
 
```
