---
title: "Plotting_Comparison_Metrics"
author: "Shaurya Jauhari"
date: "3/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Prioritization Plot | Import the score table from file.}

prioritization_score_table <- read.table("./Prioritization_Table.txt", sep = "\t", header = TRUE, quote = "")
#jpeg(file="Prioritization.jpeg")
prioritization_score_table <- prioritization_score_table[,c(5,10,15,20)]
boxplot(prioritization_score_table, ylab = "Prioritization", xlab = "Enrichment Method",col = c("salmon","tan","khaki","lavender"), boxwex = 0.1, ylim = c(0,100), names = c("Chipenrich", "Broadenrich","Seq2pathway", "Enrichr"))
abline(prioritization_score_table , h=50, col="red")
#dev.off()
```
```{r (Surrogate) Sensitivity Plot | Import the score table from file.}

surrogate_sensitivity_table <- read.table("./Surrogate_Sensitivity_Table.txt", sep = "\t", header = TRUE, quote = "")
#jpeg(file="Surrogate_Sensitivity.jpeg")
surrogate_sensitivity_table <- surrogate_sensitivity_table[,c(5,10,15,20)]
boxplot(surrogate_sensitivity_table, ylab = "Sensitivity (P-values of Target Pathways)", xlab = "Enrichment Method",col = c("salmon","tan","khaki","lavender"), boxwex = 0.1, ylim = c(0,1), names = c("Chipenrich", "Broadenrich","Seq2pathway","Enrichr"))
abline(surrogate_sensitivity_table, h=0.5, col="red")
#dev.off()
```
```{r Sensitivity Plot | Import the score table from file.}

sensitivity_table <- read.table("./Sensitivity_Table.txt", sep = "\t", header = TRUE, quote = "")
#jpeg(file="Sensitivity.jpeg")
sensitivity_table <- sensitivity_table[,c(5,10,15,20)]
boxplot(sensitivity_table, ylab = "Sensitivity", xlab = "Enrichment Method",col = c("salmon","tan","khaki","lavender"), boxwex = 0.1, ylim = c(0,100), names = c("Chipenrich","Broadenrich","Seq2pathway","Enrichr"))
abline(sensitivity_table, h=50, col="red")
#dev.off()
```

```{r Specificity Plot | Import the score table from file.}

specificity_table <- read.table("./Specificity_Table.txt", sep = "\t", header = TRUE, quote = "")
#jpeg(file="Specificity.jpeg")
specificity_table <- specificity_table[,c(5,10,15,20)]
boxplot(specificity_table, ylab = "Specificity", xlab = "Enrichment Method",col = c("salmon","tan","khaki","lavender"), boxwex = 0.1, ylim = c(0,100), names = c("Chipenrich","Broadenrich","Seq2pathway","Enrichr"))
abline(specificity_table, h=50, col="red")
#dev.off()
```

```{r Precision Plot | Import the score table from file.}

precision_table <- read.table("./Precision_Table.txt", sep = "\t", header = TRUE, quote = "")
#jpeg(file="Precision.jpeg")
precision_table <- precision_table[,c(5,10,15,20)]
boxplot(precision_table, ylab = "Precision", xlab = "Enrichment Method",col = c("salmon","tan","khaki","lavender"), boxwex = 0.1, ylim = c(0,3), names = c("Chipenrich","Broadenrich","Seq2pathway","Enrichr"))
abline(precision_table, h=0.5, col="red")
#dev.off()
```

